name: Daily Build

on:
    schedule:
        - cron: "0 0 * * *"
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up 7zip
              run: |
                sudo apt-get update
                sudo apt-get install p7zip-full -y

            - uses: oven-sh/setup-bun@v2
              with:
                bun-version: latest

            - name: Install bun dependencies
              run: bun i

            - name: Run index.ts
              run: bun run index.ts

            - name: Commit changes
              run: |
                git config --local user.email "action@github.com"
                git config --local user.name "GitHub Action"
                git add .
                git commit -m "Auto-commit changes"
                git push