name: Daily Check

on:
    schedule:
        - cron: "0 0 * * *"
    workflow_dispatch:

jobs:
    check:
        runs-on: ubuntu-latest

        permissions:
            contents: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up 7zip
              run: |
                sudo apt-get update
                sudo apt-get install p7zip-full -y

            - uses: oven-sh/setup-bun@v2
              with:
                bun-version: latest

            - name: Install bun dependencies
              run: bun i

            - name: Run index.ts
              env:
                DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
                UPDATE_MESSAGE: ${{ secrets.UPDATE_MESSAGE }}
              run: bun run index.ts

            - uses: stefanzweifel/git-auto-commit-action@v5